### ISSUE TITLE
Error while trying to run it 

### ISSUE THREAD

**Issue by mani246** [greengerong/maven-ng-protractor#5]
Hello , 

I am new protractor . When I am trying to install the Demo Project . Its not creating the node modules in my local directory so showing this error. 

aven-ng-protractor-master/demo/node_modules/protractor/bin/protractor": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.greengerong.ProtractorService.exec(ProtractorService.java:34)
	at com.github.greengerong.NgProtractor.execute(NgProtractor.java:86)

**Comment by neo182** [comment]
Hey aditi246,

Me too could not get the the demo running.  I got following error when I tried - mvn clean install 

Failed to execute goal com.github.greengerong:maven-ng-protractor:0.0.1:run (ng-protractor) on project maven-ng-protractor-demo: There were exceptions when run protractor test. There were protractor test failures. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.greengerong:maven-ng-protractor:0.0.1:run (ng-protractor) on project maven-ng-protractor-demo: There were exceptions when run protractor test.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: There were exceptions when run protractor test.
        at com.github.greengerong.NgProtractor.execute(NgProtractor.java:88)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.RuntimeException: There were protractor test failures.
        at com.github.greengerong.ProtractorService.dealFailures(ProtractorService.java:48)
        at com.github.greengerong.ProtractorService.exec(ProtractorService.java:36)
        at com.github.greengerong.NgProtractor.execute(NgProtractor.java:86)
        ... 21 more

**Comment by neo182** [comment]
Finally I got running protractor test with this plugin. :+1: 
Please use following configuratons for protractor.conf.js :

```
exports.config = {
    allScriptsTimeout: 11000,
    specs: [
        'e2e/*.js'
    ],
    capabilities: {
        browserName: 'chrome'
    },
    directConnect: true,
    baseUrl: 'http://localhost:8080/<YourProjectName>',
    onPrepare: function () {
        browser.driver.manage().window().maximize();
    },
    framework: 'jasmine',
    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: {
        showColors: true, // Use colors in the command line report.
        isVerbose: true, //display spec names as they are being executed
        includeStackTrace: true, //print stack trace when things go wrong
    }

};
```
